import Head from 'next/head';

import Layout from './components/core/layout';
import Search from './components/search';
import FavoritedGists from './components/favorited-gists';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Gists</title>
        <meta name='view and favorite gists' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Search />
      <FavoritedGists />
    </Layout>
  );
}
